name: Push to main on dai-deploy-common plugin

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/dai-common/**/README*'
      - 'plugins/dai-common/**/*.md'

jobs:
  call-ci-workflow:
    name: Run build & test for dai-common plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-common