name: Github Publish dai-deploy-common plugin

on:
  workflow_dispatch:
    push:
      branches: [ "main" ]
      paths-ignore:
        # Ignore changes to READMEs and other Markdown.
        - 'plugins/dai-common/**/README*'
        - 'plugins/dai-common/**/*.md'

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-common
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-common
      plugin:  dai-common
      tag-skip: true
      default-release: prerelease
      skip-release: true
  github-publish:
    uses: ./.github/workflows/github-publish.yaml
    needs: [ version-tag ]
    with:
      plugin-path: ./plugins/dai-common
