name: Pull requests for dai-deploy plugins

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/**/**/README*'
      - 'plugins/**/**/*.md'

jobs:
  ci-workflow:
    name: Build, test all plugins
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:    
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: dai-common - Install dependencies
      working-directory: ./plugins/dai-common
      run: yarn install
    - name: dai-common - Run tsc
      working-directory: ./plugins/dai-common
      run: yarn tsc
    - name: dai-common - Run lint
      working-directory: ./plugins/dai-common
      run: yarn lint  
    - name: dai-common - Build
      working-directory: ./plugins/dai-common
      run: yarn build
    - name: dai-common - Run tests
      working-directory: ./plugins/dai-common
      run: yarn test
